"""
Filename: mathsquiz.py
Author: Ronit Rathore
Date: July 2022
Description: This program will ask the user a maths question and they will enter an answer. If the asnwer is wrong then he computer will tell them so and if it's right then they will also be told so.
A menu will also be added so the user can be greeted and asked to see if they want to play or not
"""

import time
import random

VALID_CHOICE = ["yes","no"]
numbers = ["1","2","3","4","5","6","7","8","9","10"]
operators = ["+","-","x","/"]



#greet the user and ask them if they want to play or not
user_name = input("hello what's your name: ")
user_name = print("hello",user_name,)
print("      ")
print("""this is a maths quiz that will be randomly generated by the computer,
would you like to play, yes or no""")
print("  ")
menu_choice = input("please enter either yes or no: ")



#validate their input
#print a message depending on their input
while not menu_choice in VALID_CHOICE:
    menu_choice = input("please enter either yes or no")
if menu_choice == "no":
    print("goodbye")
else:
    print("let's begin")



    #randomly generate a maths question
    #validate their input and tell the user if they got it right or not
    time.sleep(1)
    rand = random.choice(numbers)
    rand2 = random.choice(numbers)
    operation = random.choice(operators)
    maths = eval(str(rand) + (operation) + str(rand2))
    print("what is",rand,operation,rand2)
    question = int(input("What is your answer:"))
    if question==maths:
        print("correct")
    else:
        print("incorrect, the right answer was",maths)
    
        

    

      
    
